name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish_shared:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno cache --node-modules-dir src/index.ts
        working-directory: ./packages/shared
      - run: deno publish
        working-directory: ./packages/shared
  publish_system:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno cache --node-modules-dir src/index.ts
        working-directory: ./packages/system
      - run: deno publish
        working-directory: ./packages/system
